JCA-63: Rond documentation review
rond-authz/rond-authz.github.io pull request #60
Opened 2022-12-29 17:06 UTC by danielemarostica

- added few examples on how to write policies
- added few technical details
- references to x-permission header have been updated to x-rond

2022-12-29 17:17 UTC, fredmaggiowski requested changes

2022-12-29 17:17 UTC, fredmaggiowski commented on _docs/configuration.md
> +                "x-rond": {
x-permission and x-rond have different schemas, we should provide both in the docs, giving more focus to the new one (x-rond) and telling from which version it is available. x-permission should be still documented for older versions.


[Here is an example of the newer configuration format](https://github.com/rond-authz/rond/blob/main/mocks/rondOasConfig.json#L5)

2022-12-29 17:17 UTC, fredmaggiowski commented on _docs/policy-integration.md
> +NOTE: When defining your `allow` policy in the `x-rond` attribute, you may want to use a `.` character to specify a namespace for your permissions:
This note is not true, please remove it alltogether with the example below; policies can not have dots in their name.

The reason for this note was a feature supported in one of the earliest versions of rond (maybe 0.2.0) where the policy to be executed where defined by the permission name; however we discarded that design in favour of the x-permission.allow (and now x-rond.requestFlow.policyName) configuration

2022-12-29 17:17 UTC, fredmaggiowski commented on _docs/policy-integration.md
> +```rego
i would not duplicate the example here; let's just provide the user the hint and link to the built-int function

2022-12-29 17:17 UTC, fredmaggiowski commented on _docs/policy-integration.md
> +These kind of checks are known as `Rows Filtering`, more details below.
This is not true; "Rows Filtering" feature is the capability to generate queries from the policy code; RBAC data (which is retrieved when the variables MONGODB_URL; etc) is a completely different feature set.

2022-12-29 17:17 UTC, fredmaggiowski commented on _docs/policy-integration.md
> +## Rows Filtering
I'd tell this (and also the response filter) before talking about RBAC

2022-12-29 17:17 UTC, fredmaggiowski commented on _data/toc.yml
> +        - title: Rego Package
These section are a bit redundant; I'd set in this menu just:

* Rego Input
* Rego policies 101
* Custom built-Ins
* RBAC Data Model

2022-12-30 09:34 UTC, MIA-Deltat1995 commented on _docs/policy-integration.md
> +filter_response_example[result] {
Mettiamo una citazione alla generazione dei sets di rego (https://www.openpolicyagent.org/docs/latest/policy-language/#generating-sets) per spiegare che le policy di response filtering devo generare un set. Al momento viene preso solo il primo elemento di questo set e viene ritornato come nuova risposta all'utente

2022-12-30 14:50 UTC, MIA-Deltat1995 commented on _docs/configuration.md
> +        "policy": "name_of_the_policy_to_execute_upon_API_invocation"
In realtà è il nome della policy che viene eseguita in risposta. Non riporterei la stessa descrizione della policy allow

2022-12-30 14:50 UTC, MIA-Deltat1995 commented on _docs/configuration.md
> +        "enableResourcePermissionsMapOptimization": false
Qui mancano le descrizioni

2022-12-30 15:06 UTC, danielemarostica commented on _docs/configuration.md
> +        "enableResourcePermissionsMapOptimization": false
improved descriptions for x-rond fields

2022-12-30 15:06 UTC, danielemarostica commented on _docs/policy-integration.md
> +filter_response_example[result] {
added link to OPA documentation for sets

2022-12-30 15:07 UTC, danielemarostica commented on _data/toc.yml
> +        - title: Rego Package
Fixed, I kept only these 4 sections

2022-12-30 15:08 UTC, danielemarostica commented on _docs/policy-integration.md
> +## Rows Filtering
Moved RBAC section to the end :+1:

2022-12-30 15:12 UTC, danielemarostica commented on _docs/configuration.md
> +                "x-rond": {
both x-permission and x-rond are now documented

2022-12-30 15:14 UTC, danielemarostica commented on _docs/policy-integration.md
> +```rego
removed duplicated example

2022-12-30 15:15 UTC, danielemarostica commented on _docs/policy-integration.md
> +NOTE: When defining your `allow` policy in the `x-rond` attribute, you may want to use a `.` character to specify a namespace for your permissions:
Improved description

2022-12-30 15:16 UTC, danielemarostica commented on _docs/policy-integration.md
> +These kind of checks are known as `Rows Filtering`, more details below.
improved description

2022-12-30 16:03 UTC, fredmaggiowski commented on _docs/configuration.md
> +        "policy": "name_of_the_policy_to_execute_upon_API_invocation"
```suggestion
        "policy": "name_of_the_policy_to_execute_during_API_response"
```

2022-12-30 16:13 UTC, danielemarostica commented on _docs/configuration.md
> +    "allow": "name_of_the_policy_to_execute_upon_API_invocation", // Required.
```suggestion
    "allow": "name_of_the_policy_to_execute_BEFORE_API_invocation", // Required.
```

2022-12-30 16:13 UTC, danielemarostica commented on _docs/configuration.md
> +        "policy": "name_of_the_policy_to_execute_upon_API_invocation"
```suggestion
        "policy": "name_of_the_policy_to_execute_AFTER_API_invocation"
```

2022-12-30 16:18 UTC, fredmaggiowski requested changes

2022-12-30 16:18 UTC, fredmaggiowski commented on _docs/configuration.md
> +  content="For Rönd versions **older than 1.5**, when defining the `resourceFilter` attribute, Rönd changes the behavior of the `allow` policy.
Why older than 1.5? I mean, the field had this name before but the feature is still the same; I think this alert is a bit misleading

2022-12-30 16:18 UTC, fredmaggiowski commented on _docs/policy-integration.md
> +  content="Since the **`.` character is not supported by Rego** in the policy name, we suggest to use `_` character when defining policy names:"
I'd remove this warning, it makes no sense: `.` is not supported therefore the one provided is a useless suggestion.

It's like suggesting not to use `.` in function names in JavaScript and use the `_` instead; you couldn't use the `.` at all so what is the suggestion about?

This concept is still biased from that older rönd version I told you in my previous review but is meaningless now

2022-12-30 16:18 UTC, fredmaggiowski commented on _docs/policy-integration.md
> +For a more complete set of available functions please check out the [Rönd cheat-sheet](https://rond-authz.io/docs/cheat-sheet).
can we use relative links for this; so it does not depend on the current domain URL

2022-12-30 16:18 UTC, fredmaggiowski commented on _docs/policy-integration.md
> +Sometimes you need to filter out some results basing on the rights or on the role of the current user.
what are "the rights" in the context of Rönd? I'd simply state something like:

```suggestion
Sometimes you need to filter out some results based on the user privileges.  
```

2022-12-30 16:18 UTC, fredmaggiowski commented on _docs/policy-integration.md
> +Sometimes you need to filter out or manipulate some fields in the response before sending it to the final target. This case is known as `Response Filtering`.
```suggestion
Sometimes you need to filter out or manipulate some fields in the response before sending it to the client This case is known as `Response Filtering`.  
```

2022-12-30 16:18 UTC, fredmaggiowski commented on _docs/policy-integration.md
> +policy_name[return_value]{
```suggestion
policy_name [return_value] {
```

2022-12-30 16:18 UTC, fredmaggiowski commented on _docs/policy-integration.md
> +filter_response_example[result] {
```suggestion
filter_response_example [result] {
```

2022-12-30 16:18 UTC, fredmaggiowski commented on _docs/policy-integration.md
> +Any RBAC policy is provided with the iterable `data.resources[_]`. This structure is used to build up the query.
`data.resources` is not related to RBAC in any way. `data.resources` is used for request query generation. 

The RBAC feature simply automatically loads user roles and bindings from the configured Database based on the user that is performing the request. roles and bindings are loaded and set in the `input.user` object

2022-12-30 16:18 UTC, fredmaggiowski commented on _docs/policy-integration.md
> +### RBAC Policies for permission evaluation
This section does not provide any example of RBAC permission evaluation; I think there is still some confusion about policy evaluation and how RBAC takes place in Rönd. They are two orthogonal features.

Policy evaluation is the essence of the service, it is meant to intercept requests and evaluate policy to let you define API access.

These policies have, by default, an input object that gives all the information about the request (and the response, during the reponse flow); with these information you can write policies that are aware of the request context. 

RBAC is an additional feature, a well-defined data model (with a set of specific management API, when in standalone mode), that adds more info in the `input` object so that your policies are not only request-aware but also aware of the user roles that are defined in the RBAC datastore.

2022-12-30 16:40 UTC, danielemarostica commented on _docs/configuration.md
> +  content="For Rönd versions **older than 1.5**, when defining the `resourceFilter` attribute, Rönd changes the behavior of the `allow` policy.
@fredmaggiowski shall i remove just the final part of the sentence?
"Rönd changes the behavior of the `allow` policy."

2022-12-30 16:40 UTC, danielemarostica commented on _docs/configuration.md
> +  content="For Rönd versions **older than 1.5**, when defining the `resourceFilter` attribute, Rönd changes the behavior of the `allow` policy.
```suggestion
  content="For Rönd versions **older than 1.5**, you should define the `resourceFilter` attribute.  
```

2022-12-30 18:01 UTC, danielemarostica commented on _docs/policy-integration.md
> +For a more complete set of available functions please check out the [Rönd cheat-sheet](https://rond-authz.io/docs/cheat-sheet).
```suggestion
For a more complete set of available functions please check out the [Rönd cheat-sheet](/docs/cheat-sheet).  
```

2022-12-30 18:02 UTC, danielemarostica commented on _docs/policy-integration.md
> +For a more complete set of available functions please check out the [Rönd cheat-sheet](https://rond-authz.io/docs/cheat-sheet).
```suggestion
For a more complete set of available functions please check out the [Rönd cheat-sheet](/docs/cheat-sheet).  
```

2022-12-30 18:06 UTC, danielemarostica commented on _docs/policy-integration.md
> +For a more complete set of available functions please check out the [Rönd cheat-sheet](https://rond-authz.io/docs/cheat-sheet).
fixed link

2022-12-30 18:06 UTC, danielemarostica commented on _docs/policy-integration.md
> +  content="Since the **`.` character is not supported by Rego** in the policy name, we suggest to use `_` character when defining policy names:"
removed misleading warning

2023-01-09 16:52 UTC, fredmaggiowski commented on _docs/policy-integration.md
> +filter_projects_example {
```
has_read_permission {
  roles := input.user.roles[_]
  roles.permissions[_] == "can_read"
}
```

2023-01-09 16:54 UTC, fredmaggiowski commented on _docs/policy-integration.md
> +   resource.name == input.user
```suggestion
   resource.name == input.user.userId
```

2023-01-10 10:16 UTC, fredmaggiowski requested changes

2023-01-10 10:16 UTC, fredmaggiowski commented on _docs/policy-integration.md
> +         "request": { "path": ["resource", "654321"], },
```suggestion
         "request": { "path": ["resource", "654321"] },
```

2023-01-10 10:16 UTC, fredmaggiowski commented on _docs/policy-integration.md
> +         "user": { "userId": "123456", }
```suggestion
         "user": { "userId": "123456" }
```

2023-01-10 10:16 UTC, fredmaggiowski commented on _docs/policy-integration.md
> +   },
```suggestion
   }
```

2023-01-10 10:17 UTC, fredmaggiowski approved these changes

2023-01-10 10:17 UTC, merged